using ProtoBuf;
using System.Collections.Generic;

namespace SEWorldGenPlugin.ObjectBuilders
{
    /// <summary>
    /// Serializable object builder used to store the global settings of the plugin.
    /// Those are valid for all worlds.
    /// </summary>
    [ProtoContract]
    public class MyObjectBuilder_GlobalSettings : MyAbstractConfigObjectBuilder
    {
        public MyObjectBuilder_GlobalSettings() : base()
        {
        }

        /// <summary>
        /// A list of planet definitions, that are defined as moons for the plugin.
        /// </summary>
        [ProtoMember(1)]
        public HashSet<string> MoonDefinitions = new HashSet<string>();

        /// <summary>
        /// A list of planet definitions, that are defined as planets for the plugin.
        /// </summary>
        [ProtoMember(2)]
        public HashSet<string> GasGiantDefinitions = new HashSet<string>();

        /// <summary>
        /// A list of planet definitions, that are defined as suns for the plugin.
        /// Suns can only be generated at the center of the system.
        /// </summary>
        [ProtoMember(3)]
        public HashSet<string> SunDefinitions = new HashSet<string>();

        /// <summary>
        /// A blacklist for planets. All planets on this list, will never be generated by the plugin.
        /// </summary>
        [ProtoMember(4)]
        public HashSet<string> BlacklistedPlanetDefinitions = new HashSet<string>();

        /// <summary>
        /// A list of mandatory planets. Those are prioritized over planets not on this list,
        /// except, if the system uses full random generation. Then this list is ignored.
        /// </summary>
        [ProtoMember(5)]
        public HashSet<string> MandatoryPlanetDefinitions = new HashSet<string>();

        /// <summary>
        /// Name format for planets. This is used for the generated gpss for planets.
        /// Available variables are [ObjectNumber], [ObjectNumberGreek], [ObjectNumberRoman],
        /// [ObjectLetterLower], [ObjectLetterUpper], [ObjectId].
        /// </summary>
        [ProtoMember(6)]
        public string PlanetNameFormat = "Planet [ObjectNumber]";

        /// <summary>
        /// Name format for moons. This is used for the generated gpss for moons.
        /// Available variables are [ObjectNumber], [ObjectNumberGreek], [ObjectNumberRoman],
        /// [ObjectLetterLower], [ObjectLetterUpper], [ObjectId], [MoonPlanetName].
        /// </summary>
        [ProtoMember(7)]
        public string MoonNameFormat = "Moon [ObjectNumber]";

        /// <summary>
        /// Name format for moons. This is used for the generated gpss for moons.
        /// Available variables are [ObjectNumber], [ObjectNumberGreek], [ObjectNumberRoman],
        /// [ObjectLetterLower], [ObjectLetterUpper].
        /// </summary>
        [ProtoMember(8)]
        public string BeltNameFormat = "Belt [ObjectNumberGreek]";

        /// <summary>
        /// Wether or not patches are enabled.
        /// </summary>
        [ProtoMember(9)]
        public bool EnablePatching = false;

        public override MyAbstractConfigObjectBuilder copy()
        {
            var copy = new MyObjectBuilder_GlobalSettings();

            copy.MoonDefinitions = MoonDefinitions;
            copy.GasGiantDefinitions = GasGiantDefinitions;
            copy.BlacklistedPlanetDefinitions = BlacklistedPlanetDefinitions;
            copy.MandatoryPlanetDefinitions = MandatoryPlanetDefinitions;
            copy.PlanetNameFormat = PlanetNameFormat;
            copy.MoonNameFormat = MoonNameFormat;
            copy.BeltNameFormat = BeltNameFormat;
            copy.EnablePatching = EnablePatching;

            return copy;
        }

        public override void Verify()
        {
        }
    }
}
